#!/bin/bash

# create secret
kubectl create secret generic k10store-secret \
      --namespace kasten-io \
      --type secrets.kanister.io/aws \
      --from-literal=aws_access_key_id=AKIAIOSFODNN7EXAMPLE \
      --from-literal=aws_secret_access_key=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

cat > /tmp/k10-object-location-profile.yaml <<EOF
kind: Profile
apiVersion: config.kio.kasten.io/v1alpha1
metadata:
  name: k10store
  namespace: kasten-io
spec:
  locationSpec:
    type: ObjectStore
    objectStore:
      endpoint: http://minio.minio.svc.cluster.local:9000
      name: k10-bucket
      objectStoreType: S3
    credential:
      secretType: AwsAccessKey
      secret:
        apiVersion: v1
        kind: secret
        name: k10store-secret
        namespace: kasten-io
  type: Location
EOF

kubectl apply -f /tmp/k10-object-location-profile.yaml

exit 0
