#!/bin/bash
set -euxo pipefail

while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    echo "Waiting for Instruqt to finish booting the VM"
    sleep 1
done

echo "alias k=kubectl" >> /root/.bashrc
echo "source /usr/share/bash-completion/bash_completion" >> /root/.bashrc
echo "source <(kubectl completion bash)" >> /root/.bashrc
echo "complete -F __start_kubectl k" >> /root/.bashrc

