#!/bin/bash
#
# This is a sample setup script. Rename this file to setup-$CONTAINER
# (where $container is the name of the container as defined in your config.yml),
# and replace this content with your own script.
#
# This script will be run when you setup the challenge.
#
# Remember that the exit code is important. See the documentation
# for more information.
#

helm repo add minio https://helm.min.io/
helm repo add bitnami https://charts.bitnami.com/bitnami

# Wait for Kubernetes to be up
JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'
COUNTER=60
until [ $COUNTER -lt 0 ]; do
    echo "Waiting for Kubernetes to be ready... ${COUNTER}"
    kubectl get nodes -o jsonpath="$JSONPATH" | grep "Ready=True"
    if [[ $? -eq 0 ]] ; then
        exit 0
    fi
    docker ps
    let COUNTER-=1
    sleep 5
done

exit 1
