#!/bin/bash

if ! ls ambassador-challenge.txt; then 
    fail-message "ambassador-challenge.txt can't be found"
    exit 1
fi 

if ! grep "https://$HOSTNAME-32000-$INSTRUQT_PARTICIPANT_ID.env.play.instruqt.com/k10/prometheus/graph" ambassador-challenge.txt; then
    fail-message "The Url of the promethus GUI cant be found in ambassador-challenge.txt"
    exit 1
fi

CHALLENGE_FILE="frontend-challenge.txt"
BAD_ANS=( "01" "03" "04" )
GOOD_ANS=( "02" "05")

for good in ${GOOD_ANS[@]} 
do 
    grep $good $CHALLENGE_FILE >/dev/null 2>&1
    if [[ $? -ne 0 ]]; then
        fail-message "An Accurate sentence is missing in $CHALLENGE_FILE"
        exit 1
    fi
done  

for bad in ${BAD_ANS[@]}
do 
    grep $bad $CHALLENGE_FILE >/dev/null 2>&1
    if [[ $? -eq 0 ]]; then
        fail-message "An Inaccurate sentence is in $CHALLENGE_FILE"
        exit 1
    fi
done 

exit 0
