#!/bin/bash
#
# This is a sample setup script. Rename this file to setup-$CONTAINER
# (where $container is the name of the container as defined in your config.yml),
# and replace this content with your own script.
#
# This script will be run when you setup the challenge.
#
# Remember that the exit code is important. See the documentation
# for more information.
#

cat <<EOF > csi-backup-challenge.txt
01. The snapshot created in mongodb are immediatly deleted once backup is finished 
02. The snapshot created in mongodb are keeped for local restore but deleted by the local retention policy
03. PVC created in kasten-io during the execution of the backup are immediatly deleted once backup is finished 
04. PVC created in kasten-io during the execution of the backup are keeped for local restore but deleted by the local retention policy
05. PVC created in kasten-io during the execution of the backup are cloned from the snapshot and used by the datamover
EOF

cat <<EOF > csi-backup-challenge-readonly.txt
01. The snapshot created in mongodb are immediatly deleted once backup is finished 
02. The snapshot created in mongodb are keeped for local restore but deleted by the local retention policy
03. PVC created in kasten-io during the execution of the backup are immediatly deleted once backup is finished 
04. PVC created in kasten-io during the execution of the backup are keeped for local restore but deleted by the local retention policy
05. PVC created in kasten-io during the execution of the backup are cloned from the snapshot and used by the datamover
EOF