version: "3"
virtualmachines:
- name: k8svm
  image: k10-gke-testdrive-180621/instruqt-k8s-testdrive-02-2022-v2
  shell: /bin/bash
  machine_type: n1-standard-8
  allow_external_ingress:
  - http
  - https
  - high-ports
- name: nfs
  image: k10-gke-testdrive-180621/instruqt-k8s-testdrive-02-2022-v2
  shell: /bin/bash
  machine_type: n1-standard-8
  allow_external_ingress:
  - http
  - https
  - high-ports
